### ISSUE TITLE
Error in an Ionic project

### ISSUE THREAD

**Issue by brentrobbins** [nparashuram/virtual-device-wall#3]
I tired this on an Ionic project and it didn't seem to work after I ran "node_modules/.bin/wall --appetize=APPETIZE_KEY' command.

The error message:

Writing private key for ios. Keep this file safe for future updates to this app

SyntaxError: Unexpected token E
at Object.parse (native)
at setPrivateKey (/node_modules/virtual-device-wall/lib/appetize.js:34:57)
at Request._callback (/node_modules/virtual-device-wall/lib/appetize.js:56:21)
at Request.self.callback (/node_modules/virtual-device-wall/node_modules/request/request.js:198:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/node_modules/virtual-device-wall/node_modules/request/request.js:1082:10)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/node_modules/virtual-device-wall/node_modules/request/request.js:1009:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16

**Comment by axemclion** [comment]
@brentrobbins Can you delete the .privatekey.json file in the folder and try again ?

**Comment by brentrobbins** [comment]
I searched my system and it can't find a .privatekey.json file.

**Comment by axemclion** [comment]
weird - this is basically trying to write a file to that repo. The error possibly could be due to the fact that your appetize key is incorrect. If the upload to appetize worked well, you should get a JSON.

One way to see the exact error message would be to turn on `DEBUG` using `export DEBUG=vw:*`. This should print more debugging information.

**Comment by brentrobbins** [comment]
OK, I added it and here's the where it crashed with the debug info:
(removed link)

**Comment by axemclion** [comment]
Aargh, my bad. Actually, looks like we do get a response from appetize. May I ask you to look at node_modules/virtual-device-wall/lib/appetize.js and add console.log(data) at line 34. This way, we could see what the exact error is, when you are trying to run your scenario.

**Comment by brentrobbins** [comment]
Here's the full response: (removed link)

**Comment by axemclion** [comment]
@brentrobbins Thanks - helps a lot in locating the error. So this is what happens - either the ios build is not able to zip the files, or there is some sort of firewall that stops the internet from accessing your machine to upload the ios and android packages.

Can you see if there is a bin folder created in the folder where you are running this command from ? It should have an android and an ios file. If yes, then are you aware of any network/firewall restrictions on your computer/network ?

I added 2ecb17854e8d62ecf415b89d4e7f312bfe53f398 for reporting a better error message. If you update the package, you should be able to see a URL that you should try to access.

**Comment by brentrobbins** [comment]
Thanks for the update @axemclion. We're making progress! I was able to able to get the wall page loaded. What's funny is I had a meteor project running and it first loaded that page at the ngrok url, so I just had to kill that and it loaded. However the two Nexus "devices/emulators" aren't loading. Here's the screenshot: (removed link) since it's white text on that light bg it's hard to read to I'll add the errors/messages below.

## Nexus 5:

Embed your app You may use an iframe to embed your app into any HTML. Include parameters in the URL of your iframe to specify: device - iphone4s, iphone5s, iphone6, iphone6plus, ipadair, nexus5, nexus7 or nexus9scale - 25, 50, 75 or 100autoplay - true or false, default is falseorientation - portrait or landscape

## Nexus 7

Embed your app You may use an iframe to embed your app into any HTML. Include parameters in the URL of your iframe to specify: device - iphone4s, iphone5s, iphone6, iphone6plus, ipadair, nexus5, nexus7 or nexus9scale - 25, 50, 75 or 100autoplay - true or false, default is falseorientation - portrait or landscapedeviceColor - black or white, (gray or silver also work)screenOnly - true or false, default is falsexdocMsg - true or false, default is falselanguage - ISO 639-1 language codeparams - any URL-encoded JSON dictionaryGenerate the code<iframe src="https://appetize.io/embed/<PUBLIC KEY>?device=iphone5s&scale=100&autoplay=false&orientation=portrait&deviceColor=black" width="378px" height="800px" frameborder="0" scrolling="no"></iframe>

**Comment by axemclion** [comment]
Great - I think this should be easier to solve. You should now have a .private.json files that have the URLs to manage the Android Apps. Are you able to open those, and see the devices loaded?

**Comment by brentrobbins** [comment]
My bad. I needed to run my Android build and it now works. Thanks for all
your help! By the way, is there anyway to extend the timeout time?

**Comment by axemclion** [comment]
@brentrobbins We would need to ping appetize.io for that. Lets see what they tell us.

**Comment by axemclion** [comment]
Closing this issue since we got this working.

**Comment by brentrobbins** [comment]
Great, thanks again for all of your help @axemclion.
